ukf_filter_node_diff:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_acceleration: false
        predict_to_current_time: false
        publish_tf: true
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        map_frame: map
        sensor_timeout: 0.01

        odom0: /diff_cont/odom
        odom0_config:  [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 3

        imu0: /imu_sensor_broadcaster/imu
        imu0_config: [false, false, false,
                      false,  false,  true,
                      false, false, false,
                      false, false, true,
                      false, false, false]

        imu0_queue_size: 3
        imu0_differential: false
        imu0_remove_gravitational_acceleration: false

ukf_filter_node_mecanum:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true
        publish_acceleration: false
        predict_to_current_time: false
        publish_tf: true
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        sensor_timeout: 0.02

        odom0: /mecanum_drive_controller/odometry
        odom0_config:  [false, false, false,
                       false, false, false,
                       true,  true,  false,
                       false, false, false,
                       false, false, false]
        odom0_queue_size: 3
        imu0: /imu_sensor_broadcaster/imu
        imu0_config: [false, false, false,
                      false,  false,  true,
                      false, false, false,
                      false, false, false,
                      false, false, false]
        imu0_queue_size: 3
        imu0_differential: false
        imu0_remove_gravitational_acceleration: false
