nav2_velocity_smoother_for_diff_drive:
  ros__parameters:
    smoothing_frequency: 50.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 0.5]
    min_velocity: [-0.5, 0.0, -0.5]
    max_accel: [1.0, 0.0, 1.6]
    max_decel: [-1.0, 0.0, -1.6]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1000.0